def main():
    with open("lua/blink-cmp-sshconfig/completion_items.lua", "w") as fp:
        fp.write("--- Do NOT edit this file\n")
        fp.write("--- This file is autogenerated from gen_completion_items.py\n")
        fp.write("\n")
        fp.write("--- @module 'blink-cmp'\n")
        fp.write("--- @type blink.cmp.CompletionItem[]\n")
        fp.write("return {\n")
        fp.write("}\n")


if __name__ == "__main__":
    main()
