[project]
name = "blink-cmp-sshconfig"
version = "0.1.0"
description = "blink.cmp source for ssh_config(5) files"
readme = "README.md"
requires-python = ">=3.13"
dependencies = [
    "beautifulsoup4>=4.13.4",
    "requests>=2.32.3",
]
