name: uv

permissions:
  contents: read

on:
  push:
    branches:
      - main
    paths:
      - "**/*.py"
      - .python-version
      - pyproject.toml
      - uv.lock
      - .github/workflows/uv.yaml
  pull_request:
    paths:
      - "**/*.py"
      - .python-version
      - pyproject.toml
      - uv.lock
      - .github/workflows/uv.yaml

env:
  CLICOLOR: 1

jobs:
  stylua:
    name: Check python files using uv
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false

      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Lint python files using ruff
        run: uvx ruff check
